project:
  type: website
  output-dir: docs

website:
  title: "西方コンパス"
  navbar:
    background: "#40e0d0"
    logo-alt: あああ
    pinned: true
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

sidebar:
  contents: auto

format:
  html:
    theme: default
    css: styles.css



