project:
  type: website
  output-dir: docs

website:
  title: "西方コンパス"
  navbar:
    pinned: true
    right:
      - text: "Blog"
        file: blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

sidebar:
  contents: auto

format:
  html:
    theme: cosmo
    css: styles.css



